theme: jekyll-theme-cayman
title: Devarth Parikh
description: Personal Webpage

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
