theme: jekyll-theme-cayman
title: Devarth Parikh
description: Personal Webpage
social_media:
  behance: your_username
  dribbble: your_username  
  facebook: your_username
  hackerrank: your_username
  instagram: your_username
  keybase: your_username
  linkedin: your_username
